---
- hosts: all
  become: yes
  tasks: 
  - name: in this tasks , i want to install apache2 websevers on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_fimaly= "Debian"
  - name: in this tasks, i want to start apache2 websevers on ubuntu
    service:
      name: apache2
      state: started
    when: ansible_os_fimaly= "Debian"
